name: Deploy to Lambda

on:
  push:
    branches: [ master ]  # Or 'main' if your branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Zip the code
      run: zip -r function.zip index.js node_modules

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.1.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        zip_file: function.zip
      retry: 3
      retry_delay: 10